name: Test Github OIDC to AWS
on:
  push:
    branches:
      - '*'
permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout
jobs:
  test-github:
    runs-on: ubuntu-20.04
    steps:
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::388588623842:role/ContinuousIntegrationRole
          role-session-name: github-test
          aws-region: us-west-2